cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'homebrew/services'

brew 'cask'
brew 'dnsmasq'
brew 'hub'
brew 'nmap'
brew 'node'
brew 'terminal-notifier'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'

cask 'alfred'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'font-roboto-mono'
cask 'iterm2'
cask 'quip'
cask 'rescuetime'
cask 'slate'
cask 'spotify'
cask 'sublime-text'
cask 'vlc'

brew 'mas'
# Seems to get stuck forever and conflict with something else
# mas 'Xcode', id: 497799835
