cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'go'
brew 'codemod'
brew 'diff-so-fancy'
brew 'dnsmasq'
brew 'flake8'
brew 'fzf'
brew 'htop'
brew 'highlight'
brew 'hub'
brew 'lighttpd'
brew 'nmap'
brew 'node'
brew 'python3'
brew 'socat'
brew 'terminal-notifier'
brew 'tldr'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'

cask 'alfred'
cask 'caffeine'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'firefox'
# cask 'font-roboto-mono'
cask 'google-chrome'
cask 'iterm2'
cask 'java8'
cask 'karabiner-elements'
cask 'ngrok'
cask 'quip'
cask 'rescuetime'
cask 'slate'
# cask 'sonos'
cask 'spotify'
cask 'sublime-text'
cask 'transmission'
cask 'tower'
cask 'vlc'
cask 'visual-studio-code'

# QuickLook plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlimagesize'
cask 'webpquicklook'
cask 'suspicious-package'
cask 'qlvideo'

brew 'mas'
# Seems to get stuck forever and conflict with something else
# mas 'Xcode', id: 497799835
