cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'caskroom/fonts'
tap 'homebrew/services'

brew 'go'
brew 'gpg'
brew 'cask'
brew 'codemod'
brew 'dnsmasq'
brew 'flake8'
brew 'hub'
brew 'nmap'
brew 'node'
brew 'python3'
brew 'socat'
brew 'terminal-notifier'
brew 'tldr'
brew 'tree'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'

cask 'alfred'
cask 'caffeine'
cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'firefox'
# Failing right now
# cask 'font-roboto-mono'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'ngrok'
cask 'quip'
cask 'rescuetime'
cask 'slate'
cask 'sonos'
cask 'spotify'
cask 'sublime-text'
cask 'tower'
cask 'vlc'

# QuickLook plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlimagesize'
cask 'webpquicklook'
cask 'suspicious-package'
cask 'qlvideo'

brew 'mas'
# Seems to get stuck forever and conflict with something else
# mas 'Xcode', id: 497799835
