#!/bin/sh

# Install brew if needed
which -s brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install python3 if needed
which -s python3 || brew install python3

# Use python script to install the rest
python3 install-dotfiles.py
